spring.application.name=helpful_hangul

spring.datasource.url=jdbc:postgresql://localhost:5432/helpful_hangul
spring.datasource.username=sam
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

